// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Playground is the admin multi-turn LLM streaming chat UI with optional article tools.
// When enabled is false, shows configuration help instead of the form.
// toolsAvailable is true when the server wired MCP article tools.
func Playground(enabled bool, toolsAvailable bool, model string, csrfToken string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"admin-page playground-page\"><h1>LLM Streaming Playground</h1><p><a href=\"/admin\">← 文章列表</a></p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !enabled {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"meta\">尚未設定 LLM。請在 <code>.env</code> 填入 <code>WIKIBUILD_LLM_BASE_URL</code>、<code>WIKIBUILD_LLM_API_KEY</code>、 <code>WIKIBUILD_LLM_MODEL</code> 後重啟。</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<p class=\"meta\">模型：<code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(model)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/playground.templ`, Line: 18, Col: 26}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</code> · OpenAI 兼容 <code>chat/completions</code> · <strong>SSE streaming</strong> · 多輪對話 · 僅後台</p><div class=\"playground-layout\"><div class=\"playground-input\"><label for=\"pg-system\">System（可選，全程共用）</label> <textarea id=\"pg-system\" rows=\"3\" placeholder=\"你是有幫助的助理…\"></textarea> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if toolsAvailable {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<p class=\"playground-tools\"><label><input type=\"checkbox\" id=\"pg-tools\" checked> <strong>Article tools</strong>（MCP 同源：list/get/create/update/status/visibility）</label></p><p class=\"meta\">開啟後模型可透過 tool use 讀寫本站文章（create 預設 draft+private）。tool 回合期間會顯示即時進度。</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<label for=\"pg-message\">Message</label> <textarea id=\"pg-message\" rows=\"5\" placeholder=\"輸入問題…（Enter 送出，Shift+Enter 換行；中文候選確認不會送出）\"></textarea><p class=\"playground-actions\"><button type=\"button\" id=\"pg-send\" class=\"ai-seo-btn\">送出（stream）</button> <button type=\"button\" id=\"pg-stop\" class=\"ai-seo-btn\" disabled>停止</button> <button type=\"button\" id=\"pg-clear\">清除對話</button></p><input type=\"hidden\" name=\"_csrf\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(csrfToken)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/playground.templ`, Line: 42, Col: 56}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"><div id=\"pg-live\" class=\"playground-live\" hidden aria-live=\"polite\"><div class=\"playground-live-row\"><span class=\"playground-live-dot\" aria-hidden=\"true\"></span> <strong id=\"pg-live-phase\">待命</strong> <span id=\"pg-live-elapsed\" class=\"meta\">0.0s</span></div><p id=\"pg-live-detail\" class=\"meta playground-live-detail\"></p></div><p id=\"pg-status\" class=\"meta\" aria-live=\"polite\"></p></div><div class=\"playground-output-wrap\"><div class=\"playground-tabs meta\"><span>對話 / 進度 / tool 事件</span> <label class=\"playground-raw-toggle\"><input type=\"checkbox\" id=\"pg-show-raw\"> 顯示原始 Markdown</label></div><div id=\"pg-transcript\" class=\"playground-transcript\" aria-live=\"polite\"></div><pre id=\"pg-raw\" class=\"playground-raw\" hidden></pre></div></div><script src=\"https://cdn.jsdelivr.net/npm/marked@12.0.2/marked.min.js\" defer></script> <script src=\"https://cdn.jsdelivr.net/npm/dompurify@3.1.6/dist/purify.min.js\" defer></script> <script src=\"/static/js/playground.js\" defer></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
