// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Upload renders the HTML upload form. The file field accepts a .zip
// (containing index.html + assets) or a single .html file.
// raw_mode defaults to ON: multi-page zips with relative paths (css/, slides/)
// need the original document + <base href="/slug/"> to work.
func Upload(csrfToken string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>上傳 HTML</h1><p class=\"meta\">適用完整靜態頁／簡報 zip。有相對路徑（例如 <code>slides/01.html</code>、<code>css/style.css</code>）時請開 <strong>raw_mode</strong>，否則路徑會指錯。</p><form method=\"post\" action=\"/admin/upload\" enctype=\"multipart/form-data\"><input type=\"hidden\" name=\"_csrf\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(csrfToken)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin/upload.templ`, Line: 14, Col: 53}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><p><label>slug<br><input name=\"slug\" required placeholder=\"my-deck\"></label></p><p><label>標題<br><input name=\"title\" required></label></p><p><label>檔案（.zip 含 index.html 與資產，或單一 .html）<br><input name=\"file\" type=\"file\" accept=\".zip,.html,.htm\" required></label></p><p><label>狀態 <select name=\"status\"><option value=\"draft\">draft</option> <option value=\"published\" selected>published</option></select></label></p><p><label>可見性 <select name=\"visibility\"><option value=\"public\">public</option> <option value=\"protected\">protected</option> <option value=\"private\">private</option></select></label></p><p><label><input name=\"raw_mode\" type=\"checkbox\" checked> <strong>raw_mode</strong>：原檔直送（不套站台佈景）— <em>zip 多頁／有資產時建議開啟</em></label></p><p class=\"meta\">關閉 raw_mode 時會把內容塞進站台版型；仍會設定 <code>&lt;base href=\"/slug/\"&gt;</code> 以修正相對路徑，但完整簡報／自訂 CSS 通常仍建議 raw_mode。</p><p><button type=\"submit\">上傳</button></p></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
