// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArticles = `-- name: CountArticles :one
SELECT count(*) FROM articles
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR visibility = $2::text)
  AND ($3::text IS NULL OR $3::text = ANY(tags))
  AND ($4 = '' OR title ILIKE '%' || $4 || '%' OR body ILIKE '%' || $4 || '%')
`

type CountArticlesParams struct {
	Status     pgtype.Text
	Visibility pgtype.Text
	Tag        pgtype.Text
	Search     interface{}
}

func (q *Queries) CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticles,
		arg.Status,
		arg.Visibility,
		arg.Tag,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    slug, title, type, status, visibility, password, raw_mode, pinned,
    body, tags, created_at, updated_at, published_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10,
    COALESCE($11, now()),
    COALESCE($12, now()),
    $13
)
RETURNING id, slug, title, type, status, visibility, password, raw_mode, pinned, body, tags, created_at, updated_at, published_at
`

type CreateArticleParams struct {
	Slug        string
	Title       string
	Type        string
	Status      string
	Visibility  string
	Password    string
	RawMode     bool
	Pinned      bool
	Body        string
	Tags        []string
	CreatedAt   interface{}
	UpdatedAt   interface{}
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Slug,
		arg.Title,
		arg.Type,
		arg.Status,
		arg.Visibility,
		arg.Password,
		arg.RawMode,
		arg.Pinned,
		arg.Body,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Visibility,
		&i.Password,
		&i.RawMode,
		&i.Pinned,
		&i.Body,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, slug, title, type, status, visibility, password, raw_mode, pinned, body, tags, created_at, updated_at, published_at FROM articles WHERE id = $1
`

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Visibility,
		&i.Password,
		&i.RawMode,
		&i.Pinned,
		&i.Body,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT id, slug, title, type, status, visibility, password, raw_mode, pinned, body, tags, created_at, updated_at, published_at FROM articles WHERE slug = $1
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Visibility,
		&i.Password,
		&i.RawMode,
		&i.Pinned,
		&i.Body,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, slug, title, type, status, visibility, password, raw_mode, pinned, body, tags, created_at, updated_at, published_at FROM articles
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR visibility = $2::text)
  AND ($3::text IS NULL OR $3::text = ANY(tags))
  AND ($4 = '' OR title ILIKE '%' || $4 || '%' OR body ILIKE '%' || $4 || '%')
ORDER BY pinned DESC, id DESC
LIMIT NULLIF($6, 0) OFFSET $5
`

type ListArticlesParams struct {
	Status     pgtype.Text
	Visibility pgtype.Text
	Tag        pgtype.Text
	Search     interface{}
	Skip       int32
	MaxRows    interface{}
}

// Optional filters: pass NULL (Valid=false) to skip status/visibility/tag,
// pass ” search to skip full-text search. limit=0 means "no limit".
func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.Status,
		arg.Visibility,
		arg.Tag,
		arg.Search,
		arg.Skip,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.Visibility,
			&i.Password,
			&i.RawMode,
			&i.Pinned,
			&i.Body,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles SET
    slug         = $1,
    title        = $2,
    type         = $3,
    status       = $4,
    visibility   = $5,
    password     = $6,
    raw_mode     = $7,
    pinned       = $8,
    body         = $9,
    tags         = $10,
    updated_at   = COALESCE($11, now()),
    published_at = $12
WHERE id = $13
RETURNING id, slug, title, type, status, visibility, password, raw_mode, pinned, body, tags, created_at, updated_at, published_at
`

type UpdateArticleParams struct {
	Slug        string
	Title       string
	Type        string
	Status      string
	Visibility  string
	Password    string
	RawMode     bool
	Pinned      bool
	Body        string
	Tags        []string
	UpdatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	ID          int64
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.Slug,
		arg.Title,
		arg.Type,
		arg.Status,
		arg.Visibility,
		arg.Password,
		arg.RawMode,
		arg.Pinned,
		arg.Body,
		arg.Tags,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Visibility,
		&i.Password,
		&i.RawMode,
		&i.Pinned,
		&i.Body,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}
