// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArticles = `-- name: CountArticles :one
SELECT count(*) FROM articles
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR visibility = $2::text)
  AND ($3::text IS NULL OR $3::text = ANY(tags))
  AND ($4 = '' OR title ILIKE '%' || $4 || '%' OR body ILIKE '%' || $4 || '%')
`

type CountArticlesParams struct {
	Status     pgtype.Text
	Visibility pgtype.Text
	Tag        pgtype.Text
	Search     interface{}
}

func (q *Queries) CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticles,
		arg.Status,
		arg.Visibility,
		arg.Tag,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    slug, title, type, status, visibility, password, raw_mode, pinned, show_toc,
    body, tags, seo_title, summary, meta_description, cover_image_url, og_image_url,
    created_at, updated_at, published_at, publish_at, preview_token
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16,
    COALESCE($17, now()),
    COALESCE($18, now()),
    $19,
    $20,
    $21
)
RETURNING id, slug, title, type, status, visibility, password, raw_mode, pinned, show_toc, body, tags, seo_title, summary, meta_description, cover_image_url, og_image_url, created_at, updated_at, published_at, publish_at, preview_token
`

type CreateArticleParams struct {
	Slug            string
	Title           string
	Type            string
	Status          string
	Visibility      string
	Password        string
	RawMode         bool
	Pinned          bool
	ShowToc         bool
	Body            string
	Tags            []string
	SeoTitle        string
	Summary         string
	MetaDescription string
	CoverImageUrl   string
	OgImageUrl      string
	CreatedAt       interface{}
	UpdatedAt       interface{}
	PublishedAt     pgtype.Timestamptz
	PublishAt       pgtype.Timestamptz
	PreviewToken    string
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Slug,
		arg.Title,
		arg.Type,
		arg.Status,
		arg.Visibility,
		arg.Password,
		arg.RawMode,
		arg.Pinned,
		arg.ShowToc,
		arg.Body,
		arg.Tags,
		arg.SeoTitle,
		arg.Summary,
		arg.MetaDescription,
		arg.CoverImageUrl,
		arg.OgImageUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.PublishAt,
		arg.PreviewToken,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Visibility,
		&i.Password,
		&i.RawMode,
		&i.Pinned,
		&i.ShowToc,
		&i.Body,
		&i.Tags,
		&i.SeoTitle,
		&i.Summary,
		&i.MetaDescription,
		&i.CoverImageUrl,
		&i.OgImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.PublishAt,
		&i.PreviewToken,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, slug, title, type, status, visibility, password, raw_mode, pinned, show_toc, body, tags, seo_title, summary, meta_description, cover_image_url, og_image_url, created_at, updated_at, published_at, publish_at, preview_token FROM articles WHERE id = $1
`

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Visibility,
		&i.Password,
		&i.RawMode,
		&i.Pinned,
		&i.ShowToc,
		&i.Body,
		&i.Tags,
		&i.SeoTitle,
		&i.Summary,
		&i.MetaDescription,
		&i.CoverImageUrl,
		&i.OgImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.PublishAt,
		&i.PreviewToken,
	)
	return i, err
}

const getArticleByPreviewToken = `-- name: GetArticleByPreviewToken :one
SELECT id, slug, title, type, status, visibility, password, raw_mode, pinned, show_toc, body, tags, seo_title, summary, meta_description, cover_image_url, og_image_url, created_at, updated_at, published_at, publish_at, preview_token FROM articles WHERE preview_token = $1 AND preview_token <> ''
`

func (q *Queries) GetArticleByPreviewToken(ctx context.Context, previewToken string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleByPreviewToken, previewToken)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Visibility,
		&i.Password,
		&i.RawMode,
		&i.Pinned,
		&i.ShowToc,
		&i.Body,
		&i.Tags,
		&i.SeoTitle,
		&i.Summary,
		&i.MetaDescription,
		&i.CoverImageUrl,
		&i.OgImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.PublishAt,
		&i.PreviewToken,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT id, slug, title, type, status, visibility, password, raw_mode, pinned, show_toc, body, tags, seo_title, summary, meta_description, cover_image_url, og_image_url, created_at, updated_at, published_at, publish_at, preview_token FROM articles WHERE slug = $1
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Visibility,
		&i.Password,
		&i.RawMode,
		&i.Pinned,
		&i.ShowToc,
		&i.Body,
		&i.Tags,
		&i.SeoTitle,
		&i.Summary,
		&i.MetaDescription,
		&i.CoverImageUrl,
		&i.OgImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.PublishAt,
		&i.PreviewToken,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, slug, title, type, status, visibility, password, raw_mode, pinned, show_toc, body, tags, seo_title, summary, meta_description, cover_image_url, og_image_url, created_at, updated_at, published_at, publish_at, preview_token FROM articles
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR visibility = $2::text)
  AND ($3::text IS NULL OR $3::text = ANY(tags))
  AND ($4 = '' OR title ILIKE '%' || $4 || '%' OR body ILIKE '%' || $4 || '%')
ORDER BY pinned DESC, id DESC
LIMIT NULLIF($6, 0) OFFSET $5
`

type ListArticlesParams struct {
	Status     pgtype.Text
	Visibility pgtype.Text
	Tag        pgtype.Text
	Search     interface{}
	Skip       int32
	MaxRows    interface{}
}

// Optional filters: pass NULL (Valid=false) to skip status/visibility/tag,
// pass ” search to skip full-text search. limit=0 means "no limit".
func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.Status,
		arg.Visibility,
		arg.Tag,
		arg.Search,
		arg.Skip,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.Visibility,
			&i.Password,
			&i.RawMode,
			&i.Pinned,
			&i.ShowToc,
			&i.Body,
			&i.Tags,
			&i.SeoTitle,
			&i.Summary,
			&i.MetaDescription,
			&i.CoverImageUrl,
			&i.OgImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.PublishAt,
			&i.PreviewToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueScheduled = `-- name: ListDueScheduled :many
SELECT id, slug, title, type, status, visibility, password, raw_mode, pinned, show_toc, body, tags, seo_title, summary, meta_description, cover_image_url, og_image_url, created_at, updated_at, published_at, publish_at, preview_token FROM articles
WHERE status = 'draft'
  AND publish_at IS NOT NULL
  AND publish_at <= $1
ORDER BY publish_at ASC
`

// Drafts whose scheduled publish time has arrived (or is past).
func (q *Queries) ListDueScheduled(ctx context.Context, now pgtype.Timestamptz) ([]Article, error) {
	rows, err := q.db.Query(ctx, listDueScheduled, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.Visibility,
			&i.Password,
			&i.RawMode,
			&i.Pinned,
			&i.ShowToc,
			&i.Body,
			&i.Tags,
			&i.SeoTitle,
			&i.Summary,
			&i.MetaDescription,
			&i.CoverImageUrl,
			&i.OgImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.PublishAt,
			&i.PreviewToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles SET
    slug          = $1,
    title         = $2,
    type          = $3,
    status        = $4,
    visibility    = $5,
    password      = $6,
    raw_mode      = $7,
    pinned        = $8,
    show_toc      = $9,
    body          = $10,
    tags          = $11,
    seo_title         = $12,
    summary           = $13,
    meta_description  = $14,
    cover_image_url   = $15,
    og_image_url      = $16,
    updated_at    = COALESCE($17, now()),
    published_at  = $18,
    publish_at    = $19,
    preview_token = $20
WHERE id = $21
RETURNING id, slug, title, type, status, visibility, password, raw_mode, pinned, show_toc, body, tags, seo_title, summary, meta_description, cover_image_url, og_image_url, created_at, updated_at, published_at, publish_at, preview_token
`

type UpdateArticleParams struct {
	Slug            string
	Title           string
	Type            string
	Status          string
	Visibility      string
	Password        string
	RawMode         bool
	Pinned          bool
	ShowToc         bool
	Body            string
	Tags            []string
	SeoTitle        string
	Summary         string
	MetaDescription string
	CoverImageUrl   string
	OgImageUrl      string
	UpdatedAt       pgtype.Timestamptz
	PublishedAt     pgtype.Timestamptz
	PublishAt       pgtype.Timestamptz
	PreviewToken    string
	ID              int64
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.Slug,
		arg.Title,
		arg.Type,
		arg.Status,
		arg.Visibility,
		arg.Password,
		arg.RawMode,
		arg.Pinned,
		arg.ShowToc,
		arg.Body,
		arg.Tags,
		arg.SeoTitle,
		arg.Summary,
		arg.MetaDescription,
		arg.CoverImageUrl,
		arg.OgImageUrl,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.PublishAt,
		arg.PreviewToken,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Visibility,
		&i.Password,
		&i.RawMode,
		&i.Pinned,
		&i.ShowToc,
		&i.Body,
		&i.Tags,
		&i.SeoTitle,
		&i.Summary,
		&i.MetaDescription,
		&i.CoverImageUrl,
		&i.OgImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.PublishAt,
		&i.PreviewToken,
	)
	return i, err
}
