// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          int64
	Slug        string
	Title       string
	Type        string
	Status      string
	Visibility  string
	Password    string
	RawMode     bool
	Body        string
	Tags        []string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
