// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArticle(ctx context.Context, id int64) error
	GetArticle(ctx context.Context, id int64) (Article, error)
	GetArticleBySlug(ctx context.Context, slug string) (Article, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Optional filters: pass NULL (Valid=false) to skip status/visibility/tag,
	// pass '' search to skip full-text search. limit=0 means "no limit".
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
}

var _ Querier = (*Queries)(nil)
