// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redirects.sql

package sqlc

import (
	"context"
)

const createRedirect = `-- name: CreateRedirect :one
INSERT INTO redirects (from_path, to_path, created_at)
VALUES (
    $1, $2,
    COALESCE($3, now())
)
ON CONFLICT (from_path) DO UPDATE SET
    to_path = EXCLUDED.to_path
RETURNING id, from_path, to_path, created_at
`

type CreateRedirectParams struct {
	FromPath  string
	ToPath    string
	CreatedAt interface{}
}

func (q *Queries) CreateRedirect(ctx context.Context, arg CreateRedirectParams) (Redirect, error) {
	row := q.db.QueryRow(ctx, createRedirect, arg.FromPath, arg.ToPath, arg.CreatedAt)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.FromPath,
		&i.ToPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRedirect = `-- name: DeleteRedirect :exec
DELETE FROM redirects WHERE from_path = $1
`

func (q *Queries) DeleteRedirect(ctx context.Context, fromPath string) error {
	_, err := q.db.Exec(ctx, deleteRedirect, fromPath)
	return err
}

const getRedirect = `-- name: GetRedirect :one
SELECT id, from_path, to_path, created_at FROM redirects WHERE from_path = $1
`

func (q *Queries) GetRedirect(ctx context.Context, fromPath string) (Redirect, error) {
	row := q.db.QueryRow(ctx, getRedirect, fromPath)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.FromPath,
		&i.ToPath,
		&i.CreatedAt,
	)
	return i, err
}

const listRedirects = `-- name: ListRedirects :many
SELECT id, from_path, to_path, created_at FROM redirects ORDER BY id DESC
`

func (q *Queries) ListRedirects(ctx context.Context) ([]Redirect, error) {
	rows, err := q.db.Query(ctx, listRedirects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Redirect
	for rows.Next() {
		var i Redirect
		if err := rows.Scan(
			&i.ID,
			&i.FromPath,
			&i.ToPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
